services:
  web:
    build: .
    environment:
      EMAIL_HOST_USER: "${EMAIL_HOST_USER}"
      EMAIL_HOST_PASSWORD: "${EMAIL_HOST_PASSWORD}"
      DEFAULT_FROM_EMAIL: "${DEFAULT_FROM_EMAIL}"
      DB_HOST: "${DB_HOST}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - .:/code
  web_migrate:
    extends:
      service: web
    command:  sh -c "sleep 15 && python /code/mysite/manage.py migrate"
    depends_on:
      - db
  web_run:
    extends:
        service: web
    command:  sh -c "sleep 15 && python /code/mysite/manage.py runserver 0.0.0.0:8000"
    ports:
        - "8000:8000"
    depends_on:
      - db
      - web_migrate
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
