# Generated by Django 5.1.1 on 2024-11-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
